### PR TITLE
averageMovie: removed as it's no longer used

### PR DESCRIPTION
**Pull request by DStrelak**
See also https://github.com/I2PC/scipion-em-xmipp/pull/603

### CODE REVIEW

**Comment by pconesa** [comment]
Just now I realized that this method is used.... here:

https://github.com/scipion-em/scipion-em-grigoriefflab/blob/ae26dad18fc21503ced373f63d64e6ddb3838750/grigoriefflab/protocols/protocol_unblur.py#L232

@azazellochg , xmipp team is reviewing and cleaning xmipp code. The are removing "xmipp_movie_alignment_correlation", therefore we are loosing averageMovie method. Used in "unblur" to do de PSD......

Is removing the option to of the PSD and option?

**Comment by azazellochg** [comment]
@pconesa grigoriefflab plugin has been deprecated years ago

**Comment by DStrelak** [comment]
> Just now I realized that this method is used.... here:
> 

That usage can be easily replaces by `xmipp_image_statistics --save_image_stats`

**Comment by pconesa** [comment]
upsss! unblurr is not in cistem anymore?

**Comment by azazellochg** [comment]
unblur is in cistem. it does not use averageMovie

**Review by pconesa — APPROVED** [review]

**Pull request merged**
