### PR TITLE
    - Chimera viewer compatible with newer versions via linking

### PR DESCRIPTION
**Pull request by pconesa**

### CODE REVIEW

**Review by azazellochg — APPROVED** [review]

**Comment by pconesa** [comment]
let me check, thanks!

**Comment by pconesa** [comment]
seems Version package does not like 11.2.safe anymore?

**Comment by azazellochg** [comment]
I think what you need to do is change the test to use "guessCudaVersion" instead, which will print a new warning and set a default version.

**Comment by pconesa** [comment]
Yes I can improve the test

**Comment by pconesa** [comment]
Should work now.... still it could be better to have a regular expression  but should cover most cases.

**Pull request merged**
