### PR TITLE
fixes in ctfStr astigmatism definition

### PR DESCRIPTION
**Pull request by fede-pe**
This PR includes:

- Fixes in CTFModes,  __str__ method. Astigmatism is equal to the defocus difference (no defocusAngle)

### CODE REVIEW

**Comment by azazellochg** [comment]
Though this is just a str method, in the current data model, astigmatism = DefocusRatio

**Comment by pconesa** [comment]
image
Maybe we should be consistent with other parts. HTML repo shows both, and astigmatism seems to be DU-DV ?

**Comment by pconesa** [comment]
Also, if we do the subtraction, it should be safe, what if one defocus, for some reason is None. We do not want this method to fail because of that.

**Comment by azazellochg** [comment]
I fully support using the difference instead of the ratio and this was raised by @rmarabini 5 years ago :) Just worries about backwards compatibility.

**Comment by fede-pe** [comment]
I have no preference for either option. Actually, I used the difference based on the definition given in the CTFFIND4 paper. Since this is an str method, where could be a problem of backwards compatibility?

**Comment by azazellochg** [comment]
I was referring to the data model in general, this PR is of course harmless.

**Review by JorMaister — APPROVED** [review]

**Pull request merged**
