### PR TITLE
Fix assign angles shifts before

### PR DESCRIPTION
**Pull request by pconesa**
This fixes 2 issues:
1.- shift in Z of projection alignment are 0 (before some value was written due to Transfor.scaleShifts working on the non inverted matrix

2.- When combining extract coordinates with assign angles final shift should be more accurate.

I'd like to discuss this with @delarosatrevin. This PR implies setting xFrac and yFrac in the Coordinate object for future alignment assign. They can be removed at alignment assign time and we can avoid asking since new attributes can be detected.

### CODE REVIEW

**Comment by pconesa** [comment]
This is unfinished, I'll push missing code today.

**Comment by pconesa** [comment]
Need to fix tests and I'll be done.

**Review by JorMaister — APPROVED** [review]

**Comment by azazellochg** [comment]
Any plans to merge this?

**Comment by delarosatrevin** [comment]
I haven't had time to properly look at it. I can try on Friday.

**Pull request merged**
