### PR TITLE
add save button to table view

### PR DESCRIPTION
**Pull request by rmarabini**
This pull request adds a "save data" button to  the tables shown by scipion using the tableView class. If you press the button the data is saved in a *.csv file and displayed using openTextFileEditor. In my computer that means using gnumeric.

No new test have been created since I do not know how to emulate a click on a button.

follows a small script to check that everything is OK

scipion3 run python
from pwem.viewers import TableView
headerList = ['name', 'surname']
dataList = [
         ('John', 'Smith') ,
         ('Larry', 'Black') ,
         ('Walter', 'White') ,
         ('Fred', 'Becker')
]

msg = 'message to be shown at the table top'
title='window title'

#NOTE: the scripts assume that there is a Logs file in the directory in which you are working. This is #always true if you are running a protocol but for this small script you will need to create the directory
import os
if not os.path.exists('Logs'):
    os.makedirs("Logs")

TableView(headerList, dataList, msg, title)

### CODE REVIEW

**Comment by azazellochg** [comment]
I'd like to test it but I couldn't find ANY plugin that is using TableView. How can I try this new button (test does not count)?

**Comment by rmarabini** [comment]
Hi Grigory,

    Some model building related protocols located  in  ccp4 and phenix
packages use TableView. For example ccp4 - refmac (or emringer or
validation cryoEM).

   If you have ccp4 plugin installed (devel version) the following test
should run refmac

    scipion3 tests
ccp4.tests.test_protocol_coot_refmac.TestRefmacRefinement2

then, select Analyze Results and finally Final Results Table.

   hope this helps

     Roberto

**Comment by rmarabini** [comment]
Hi Grigory,

    Some model building related protocols located  in  ccp4 and phenix packages use TableView. For example ccp4 - refmac (or emringer or validation cryoEM).

   If you have ccp4 plugin installed (devel version) the following test should run refmac

    scipion3 tests ccp4.tests.test_protocol_coot_refmac.TestRefmacRefinement2

then, select Analyze Results and finally Final Results Table.

   hope this helps

**Comment by rmarabini** [comment]
Hi,

    When the TableView Class was originally designed the "standard" viewer
could only use magnitudes associated to tags defined in xmipp. I understand
that this is not longer true but I do not have a clear idea regarding how
to use the "standard" viewer. Is there a viewer that can be used as
template?

The main goal of this pull request is to be able to copy the data shown in
the table and paste it in a document.
Our tables usually show two columns, in the first one we have the name of a
magnitude and in the second one the value of the magnitude. I mean:
sorting, plotting, subsettings, etc is not an issue.

**Pull request merged**
